name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 修改为 Windows 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 更新到 v4

    - name: Set up Python
      uses: actions/setup-python@v4  # 确认 v4 使用 Node.js 20
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Set up version
      id: version
      run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

    - name: Build with PyInstaller
      run: |
        pyinstaller --debug=all build.spec
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pip install pyqt5-tools  # 添加 PyQt5 相關工具


    - name: Upload artifact
      uses: actions/upload-artifact@v4  # 更新到 v4
      with:
        name: built-application
        path: dist/
