name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 更新到 v4

    - name: Set up Python
      uses: actions/setup-python@v4  # 确认 v4 使用 Node.js 20
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Set up version
      id: version
      run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

    - name: Build with PyInstaller
      run: |
        ls -al  # 列出当前目录中的所有文件，以确保 build.spec 文件存在
        pyinstaller build.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # 更新到 v4
      with:
        name: built-application
        path: dist/
